dist: bionic
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
script:
  - pylint --rcfile=.pylintrc --load-plugins pylint_quotes
  - python -m tests.run
